### ISSUE TITLE
printSent produces unnecessary newline

### ISSUE THREAD

**Issue by andrewufrank** [odanoburu/hs-conllu#8]
The function`` printSent` seems to add a newline at the beginning of a sentence (and one at the end as well) which causes the `print . read` not to be identy.  perhaps you remove the line which is commented out:

```
printSent :: Sentence -> DiffList Char
printSent ss =
  mconcat
    [ printComments (_meta ss)
--    , diffLSpace   -- causes an extra space initially  
    , printTks (_tokens ss)
    , diffLSpace
    ]
```

**Comment by odanoburu** [comment]
it's clearly a bug, I'll correct it tomorrow. thanks for the pointer!

**Comment by odanoburu** [comment]
@andrewufrank identity was only being preserved at the document level (I was checking using GNU `diff`, so that's why I didn't notice it wasn't preserved at sentence level)
